title: Java Software Engineer
author: Tien Vinh Nguyen
email: tien.workinfo@gmail.com
description: # this means to ignore newlines until "baseurl:"
  The price of excellence is discipline. The cost of mediocrity is disappointment. — William Arthur Ward

# social links
twitter_username: [TienWorkinfo](https://twitter.com/TienWorkinfo)
github_username:  [TienVNguyen](https://github.com/TienVNguyen)

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
